version: "3"
services:
  app:
    container_name: app
    build: .
    ports:
      - "3000:3000"
    links:
      - "mongo"
  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - mongodata:/data/db
      - ./setup:/setup
    ports:
      - "27017:27017"
volumes:
  mongodata:
